vision torches
xen-42/outer-wilds-new-horizons pull request #155
Opened 2022-05-24 22:24 UTC by FreezeDriedMangos

### What's new?
- ProjectionBuilder can now spawn new things (with config file support)
  - Standing Vision Torches
  - Custom targets for the Vision Torch item
- DetailBuilder now has special handling for spawning a Vision Torch item, so that it works correctly

2022-05-24 22:52 UTC, xen-42 requested changes
- Use `var` instead of writing class names looks nicer
- Use our `Logger` class instead of `Main.Instance.Modhelper` etc 
- Instead of having this separate `MakeVisionTorch` method, fix the VisionTorchItem component in the big for loop in DetailBuilder.

2022-05-25 15:48 UTC, FreezeDriedMangos commented
TODO: pull from dev
TODO: set up an optional “StartLoading” and “StartUnloading” condition on AsyncTextureLoader, and make use of that for projector stuff (require player to be in the same sector as the slides for them to start loading, and unload when the player leaves)

2022-05-25 16:16 UTC, FreezeDriedMangos commented
TODO: fix line endings in all files

2022-05-25 22:25 UTC, Bwc9876 approved these changes

2022-05-25 22:33 UTC, merged