A few miscellaneous additions
xen-42/outer-wilds-new-horizons pull request #92
Opened 2022-04-24 01:42 UTC by MegaPiggy

- Adds names to objects, textures. and materials that didn't have any.
- More Asteroid Customization
- Image Storage (so that they don't take up a ton of memory by repeatedly being created)
- Space Station Astro Object Type
- Adds the ability to stretch the mesh of a planet made with a height map
- Adds a few missing properties to schema

2022-04-24 04:52 UTC, Bwc9876 requested changes
Need to fix the type in HeightMapModule.cs

2022-04-24 04:52 UTC, Bwc9876 commented on NewHorizons/External/HeightMapModule.cs
> +        public Vector3 Stretch { get; set; } = Vector3.one;
Should be `MVector3`, not `Vector3`

2022-04-24 04:57 UTC, Bwc9876 commented
Oh uh also might wanna change this to target `dev`

2022-04-24 15:36 UTC, Bwc9876 approved these changes

2022-04-24 16:35 UTC, xen-42 requested changes
Let's remove IsSpaceStation because it doesn't seem to do anything differently than IsSatellite, and because I want to remove IsSatellite in v1.0.0 when we refactor all the config stuff. Currently all it does differently than IsMoon is it removes the minimap when you get close to the body, so it'll just be replaced with something like "HasMinimap : false".

2022-04-25 02:38 UTC, MegaPiggy commented
Done

2022-05-01 04:01 UTC, xen-42 commented
Gonna merge but I'm commenting out the texture caching stuff for now

2022-05-01 04:01 UTC, merged